---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:

    compose_version: 1.17.1
    compose_url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64"
    compose_sha256sum: db0a7b79d195dc021461d5628a8d53eeb2e556d2548b764770fccabb0a319dd8

  tasks:

    - name: install docker-compose
      get_url:
        url: "{{ compose_url }}"
        checksum: "sha256:{{ compose_sha256sum }}"
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
