---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:

    compose_version: 1.17.0
    compose_url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64"
    compose_sha256sum: b553025b82fc61547933f05693716c92967b835979ba9b092b31e50bd35e30c9

  tasks:

    - name: install docker-compose
      get_url:
        url: "{{ compose_url }}"
        checksum: "sha256:{{ compose_sha256sum }}"
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
