---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:

    compose_version: 1.22.0
    compose_url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64"
    compose_sha256sum: f679a24b93f291c3bffaff340467494f388c0c251649d640e661d509db9d57e9

  tasks:

    - name: install docker-compose
      get_url:
        url: "{{ compose_url }}"
        checksum: "sha256:{{ compose_sha256sum }}"
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
