---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: create sources.list for erlang solutions
      template:
        src: templates/etc/apt/sources.list.d/erlang_solutions.list.j2
        dest: /etc/apt/sources.list.d/erlang_solutions.list

    - name: add apt key for erlang solutions
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present

    - name: install erlang and elixir
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - esl-erlang
        - elixir
