---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: add longsleep/golang-backports PPA
      apt_repository:
        repo: "ppa:longsleep/golang-backports"

    - name: install go
      apt:
        name: golang-go
        state: present
        update_cache: yes
