---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:

    postgres_version: 11

  tasks:

    - name: install required packages
      apt:
        name: ca-certificates
        state: present
        update_cache: yes

    - name: create sources.list for postgres
      template:
        src: templates/etc/apt/sources.list.d/pgdg.list.j2
        dest: /etc/apt/sources.list.d/pgdg.list

    - name: add apt key for postgres
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: install postgres {{ postgres_version }}
      apt:
        name: postgresql-{{ postgres_version }}
        state: present
        update_cache: yes
      notify:
        - restart postgres

  handlers:

    - name: restart postgres
      service:
        name: postgresql
        state: restarted
        enabled: yes
