---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: sysctl vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 10

    - name: sysctl net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: 1024

    - name: sysctl net.core.netdev_max_backlog
      sysctl:
        name: net.core.netdev_max_backlog
        value: 1024

    - name: sysctl net.ipv4.tcp_max_syn_backlog
      sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 1024

    - name: sysctl net.ipv4.tcp_tw_reuse
      sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: 1

    - name: sysctl net.ipv4.ip_local_port_range
      sysctl:
        name: net.ipv4.ip_local_port_range
        value: 1024 65000
